---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[haproxy]
  attributes: {}
- name: lwrp
  run_list:
  - recipe[haproxy]
  - recipe[haproxy-test]
  attributes:
    haproxy:
      enable_default_http: false
      global_options: ['quiet']
      listeners:
        listen:
          lb_test:
            - balance roundrobin
            - bind 0.0.0.0:5000
            - maxconn 10
            - mode tcp
            - server netcat1 127.0.0.1:5001
            - server netcat2 127.0.0.1:5002

